### ISSUE TITLE
How to change theme icons

### ISSUE THREAD

**Issue by JohnBobbo59** [vandalsoul/dedsec-grub2-theme#12]
i would like to change my icons for uefi settings and xubuntu because uefi doesnt show an icon and xubuntu shows as ubuntu

**Comment by vandalsoul** [comment]
Hi @JohnBobbo59 
You can check out [this](https://github.com/vandalsoul/grub-tweaks#-creating-a-custom-menu-layout). If you have any doubt open and issue and ask Jacksaur (author). Hopefully he will help you out
