### ISSUE TITLE
[SOLVED] Installation script failed

### ISSUE THREAD

**Issue by eexpress** [vandalsoul/dedsec-grub2-theme#7]
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421.
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421.
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421.
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421.
./install.py: 18: Syntax error: "(" unexpected

**Comment by vandalsoul** [comment]
It's probably because of the missing shebang line in the script... I have updated the install script... or just edit `install.py` and add this on the 1st line
```
#!/usr/bin/env python3
```

**Comment by eexpress** [comment]
it works.
